[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/wb/*"
  to = "/.netlify/functions/wb?path=:splat"
  status = 200


