[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/wb/*"
  to = "/.netlify/functions/wb?path=:splat"
  status = 200

# SPA fallback (kept last so it doesn't capture /wb/*)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


